<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Chats de la chatterie
    |--------------------------------------------------------------------------
    |
    | Structure temporaire avant la création du tableau de bord.
    | Plus tard, ces données seront remplacées par une base de données
    | gérée depuis l'application interne.
    |
    | category :
    | - male
    | - female
    |
    | visibility :
    | - visible
    | - hidden
    |
    | availability :
    | - available
    | - reserved
    | - adoption_pending
    | - not_available
    | - to_define
    |
    | price_mode :
    | - hidden
    | - on_request
    | - fixed
    |
    */

    'cats' => [

        [
            'slug' => 'adamas-black-pearl-du-diamant-sauvage',
            'name' => 'Adamas Black Pearl du Diamant Sauvage',
            'short_name' => 'Adamas Black Pearl',
            'category' => 'male',
            'sex' => 'Mâle',
            'birth_date' => '2025-06-07',
            'birth_label' => '07 juin 2025',
            'icad' => '250 269 611 525 026',
            'loof' => 'LOOF 2025.31061',
            'coat' => 'Black smoke rosetted/spotted',
            'eyes' => 'Vert',
            'availability' => 'to_define',
            'availability_label' => 'À définir',
            'visibility' => 'visible',
            'price_mode' => 'hidden',
            'price' => null,
            'highlight' => 'Jeune mâle Bengal au contraste précieux, issu de lignées suivies.',
            'description' => 'Adamas Black Pearl du Diamant Sauvage est un mâle Bengal à la robe black smoke rosetted/spotted, avec un suivi santé en cours et des tests génétiques négatifs par filiation.',
            'parents' => [
                'father' => 'Bengalinstinct Vermax',
                'mother' => 'Urus du Diamant Sauvage',
            ],
            'health' => [
                'hcm' => 'En cours (juin)',
                'pkd' => 'En cours (juin)',
                'fiv_felv' => 'Négatif',
                'pra_b' => 'En cours (négatif par filiation)',
                'pkdef' => 'En cours (négatif par filiation)',
                'parents_tests' => 'PRA-b & PKDef N/N',
            ],
            'gallery' => [],
            'featured' => true,
        ],

        [
            'slug' => 'bengalinstinct-vermax',
            'name' => 'Bengalinstinct Vermax',
            'short_name' => 'Vermax',
            'category' => 'male',
            'sex' => 'Mâle',
            'birth_date' => '2024-02-29',
            'birth_label' => '29 février 2024',
            'icad' => '978 142 000 785 867',
            'loof' => 'LOOF 2025CE.500',
            'coat' => 'Brown charcoal rosetted/spotted',
            'eyes' => 'Vert',
            'availability' => 'not_available',
            'availability_label' => 'Reproducteur',
            'visibility' => 'visible',
            'price_mode' => 'hidden',
            'price' => null,
            'highlight' => 'Mâle Bengal au type marqué, avec tests santé validés.',
            'description' => 'Bengalinstinct Vermax est un mâle Bengal brown charcoal rosetted/spotted, suivi pour la reproduction avec tests HCM, PKD, FIV/FELV et génétiques renseignés.',
            'parents' => [
                'father' => 'Bengal Instinct Shere Khan',
                'mother' => 'BMKiss Jewel Blue Saphir',
            ],
            'health' => [
                'hcm' => 'OK',
                'pkd' => 'OK',
                'fiv_felv' => 'Négatif',
                'pra_b' => 'N/N',
                'pkdef' => 'N/N',
                'parents_tests' => null,
            ],
            'gallery' => [],
            'featured' => false,
        ],

        [
            'slug' => 'dottycat-gambling-man',
            'name' => 'DottyCat Gambling Man',
            'short_name' => 'Gambling Man',
            'category' => 'male',
            'sex' => 'Mâle',
            'birth_date' => '2020-07-19',
            'birth_label' => '19 juillet 2020',
            'icad' => 'À compléter',
            'loof' => 'À compléter',
            'coat' => 'À compléter',
            'eyes' => 'À compléter',
            'availability' => 'not_available',
            'availability_label' => 'Reproducteur',
            'visibility' => 'visible',
            'price_mode' => 'hidden',
            'price' => null,
            'highlight' => 'Fiche à compléter avec les informations manquantes.',
            'description' => 'Les informations complètes de DottyCat Gambling Man devront être ajoutées depuis le tableau de bord lorsque la fiche sera finalisée.',
            'parents' => [
                'father' => 'À compléter',
                'mother' => 'À compléter',
            ],
            'health' => [
                'hcm' => 'À compléter',
                'pkd' => 'À compléter',
                'fiv_felv' => 'À compléter',
                'pra_b' => 'À compléter',
                'pkdef' => 'À compléter',
                'parents_tests' => null,
            ],
            'gallery' => [],
            'featured' => false,
        ],

        [
            'slug' => 'pardusdei-tempete-du-desert',
            'name' => 'Pardusdei Tempête du Désert',
            'short_name' => 'Tempête du Désert',
            'category' => 'male',
            'sex' => 'Mâle',
            'birth_date' => '2022-07-15',
            'birth_label' => '15 juillet 2022',
            'icad' => '250 269 590 798 734',
            'loof' => 'LOOF 2022.44436',
            'coat' => 'Seal tabby mink rosetted/spotted',
            'eyes' => 'Aigue-marine',
            'availability' => 'not_available',
            'availability_label' => 'Reproducteur',
            'visibility' => 'visible',
            'price_mode' => 'hidden',
            'price' => null,
            'highlight' => 'Mâle Bengal seal mink au regard aigue-marine.',
            'description' => 'Pardusdei Tempête du Désert est un mâle Bengal seal tabby mink rosetted/spotted, suivi pour la reproduction avec tests HCM, PKD et génétiques OK.',
            'parents' => [
                'father' => 'Pardus-dei Stradivarius',
                'mother' => 'Pardus-dei Sacrilège',
            ],
            'health' => [
                'hcm' => 'OK',
                'pkd' => 'OK',
                'fiv_felv' => 'Négatif',
                'pra_b' => 'N/N',
                'pkdef' => 'N/N',
                'parents_tests' => null,
            ],
            'gallery' => [],
            'featured' => false,
        ],

        [
            'slug' => 'atomix-bomb-du-diamant-sauvage',
            'name' => 'Atomix Bomb du Diamant Sauvage',
            'short_name' => 'Atomix Bomb',
            'category' => 'female',
            'sex' => 'Femelle',
            'birth_date' => '2025-04-11',
            'birth_label' => '11 avril 2025',
            'icad' => '250 269 592 066 242',
            'loof' => 'LOOF 2025.22461',
            'coat' => 'Black silver tabby rosetted/spotted',
            'eyes' => 'Vert',
            'availability' => 'to_define',
            'availability_label' => 'À définir',
            'visibility' => 'visible',
            'price_mode' => 'hidden',
            'price' => null,
            'highlight' => 'Femelle black silver issue de lignées testées.',
            'description' => 'Atomix Bomb du Diamant Sauvage est une femelle Bengal black silver tabby rosetted/spotted, avec tests santé en cours et négatifs par filiation.',
            'parents' => [
                'father' => 'Pardus-dei Uroboros',
                'mother' => 'Tornade du Diamant Sauvage',
            ],
            'health' => [
                'hcm' => 'En cours (juin)',
                'pkd' => 'En cours (juin)',
                'fiv_felv' => 'Négatif',
                'pra_b' => 'En cours (négatif par filiation)',
                'pkdef' => 'En cours (négatif par filiation)',
                'parents_tests' => 'PRA-b & PKDef N/N',
            ],
            'gallery' => [],
            'featured' => true,
        ],

        [
            'slug' => 'zara-du-diamant-sauvage',
            'name' => 'Zara du Diamant Sauvage',
            'short_name' => 'Zara',
            'category' => 'female',
            'sex' => 'Femelle',
            'birth_date' => '2024-06-04',
            'birth_label' => '04 juin 2024',
            'icad' => '250 269 591 781 222',
            'loof' => 'LOOF 2024.37685',
            'coat' => 'Brown tabby rosetted/spotted',
            'eyes' => 'Vert',
            'availability' => 'not_available',
            'availability_label' => 'Femelle',
            'visibility' => 'visible',
            'price_mode' => 'hidden',
            'price' => null,
            'highlight' => 'Femelle brown tabby avec suivi santé complet.',
            'description' => 'Zara du Diamant Sauvage est une femelle Bengal brown tabby rosetted/spotted, issue de lignées testées avec HCM, PKD, PRA-b et PKDef OK.',
            'parents' => [
                'father' => 'Pardus-dei Tempête du Désert',
                'mother' => 'Strass du Diamant Sauvage',
            ],
            'health' => [
                'hcm' => 'OK',
                'pkd' => 'OK',
                'fiv_felv' => 'Négatif',
                'pra_b' => 'N/N',
                'pkdef' => 'N/N',
                'parents_tests' => 'PRA-b & PKDef N/N',
            ],
            'gallery' => [],
            'featured' => false,
        ],

        [
            'slug' => 'ana-du-diamant-sauvage',
            'name' => 'Ana du Diamant Sauvage',
            'short_name' => 'Ana',
            'category' => 'female',
            'sex' => 'Femelle',
            'birth_date' => '2025-03-02',
            'birth_label' => '02 mars 2025',
            'icad' => '250 269 611 367 191',
            'loof' => 'LOOF 2025.14565',
            'coat' => 'Black silver tabby rosetted/spotted',
            'eyes' => 'Vert',
            'availability' => 'to_define',
            'availability_label' => 'À définir',
            'visibility' => 'visible',
            'price_mode' => 'hidden',
            'price' => null,
            'highlight' => 'Femelle black silver au profil élégant.',
            'description' => 'Ana du Diamant Sauvage est une femelle Bengal black silver tabby rosetted/spotted, avec tests HCM et PKD OK et tests génétiques en cours par filiation.',
            'parents' => [
                'father' => 'Bengaluxe Bagheera',
                'mother' => 'Strass du Diamant Sauvage',
            ],
            'health' => [
                'hcm' => 'OK',
                'pkd' => 'OK',
                'fiv_felv' => 'Négatif',
                'pra_b' => 'En cours (négatif par filiation)',
                'pkdef' => 'En cours (négatif par filiation)',
                'parents_tests' => 'PRA-b & PKDef N/N',
            ],
            'gallery' => [],
            'featured' => false,
        ],

        [
            'slug' => 'alice-du-diamant-sauvage',
            'name' => 'Alice du Diamant Sauvage',
            'short_name' => 'Alice',
            'category' => 'female',
            'sex' => 'Femelle',
            'birth_date' => '2025-09-20',
            'birth_label' => '20 septembre 2025',
            'icad' => '250 269 611 672 990',
            'loof' => 'LOOF 2025.54813',
            'coat' => 'Black silver tabby rosetted/spotted',
            'eyes' => 'Vert',
            'availability' => 'to_define',
            'availability_label' => 'À définir',
            'visibility' => 'visible',
            'price_mode' => 'hidden',
            'price' => null,
            'highlight' => 'Jeune femelle black silver suivie avec attention.',
            'description' => 'Alice du Diamant Sauvage est une femelle Bengal black silver tabby rosetted/spotted, avec tests santé et génétiques en cours par filiation.',
            'parents' => [
                'father' => 'Pardus-dei Tempête du Désert',
                'mother' => 'Tornade du Diamant Sauvage',
            ],
            'health' => [
                'hcm' => 'En cours',
                'pkd' => 'En cours',
                'fiv_felv' => 'Négatif',
                'pra_b' => 'En cours (N/N par filiation)',
                'pkdef' => 'En cours (N/N par filiation)',
                'parents_tests' => 'PRA-b & PKDef N/N',
            ],
            'gallery' => [],
            'featured' => true,
        ],

        [
            'slug' => 'elysor-wonderful',
            'name' => 'Elysor Wonderful',
            'short_name' => 'Wonderful',
            'category' => 'female',
            'sex' => 'Femelle',
            'birth_date' => '2024-05-16',
            'birth_label' => '16 mai 2024',
            'icad' => '991 003 002 086 012',
            'loof' => 'LOOF 2025CE.183',
            'coat' => 'Seal tabby mink spotted',
            'eyes' => 'Aigue-marine',
            'availability' => 'not_available',
            'availability_label' => 'Femelle',
            'visibility' => 'visible',
            'price_mode' => 'hidden',
            'price' => null,
            'highlight' => 'Femelle seal mink au regard lumineux.',
            'description' => 'Elysor Wonderful est une femelle Bengal seal tabby mink spotted, avec suivi HCM et PKD OK, FIV/FELV négatif et tests génétiques renseignés.',
            'parents' => [
                'father' => "Karwendelberg's Kumari",
                'mother' => 'Minileo Ruth',
            ],
            'health' => [
                'hcm' => 'OK',
                'pkd' => 'OK',
                'fiv_felv' => 'Négatif',
                'pra_b' => 'N/N',
                'pkdef' => 'N/K',
                'parents_tests' => null,
            ],
            'gallery' => [],
            'featured' => false,
        ],

        [
            'slug' => 'a-queen-wild-du-diamant-sauvage',
            'name' => 'A Queen Wild du Diamant Sauvage',
            'short_name' => 'A Queen Wild',
            'category' => 'female',
            'sex' => 'Femelle',
            'birth_date' => '2025-04-11',
            'birth_label' => '11 avril 2025',
            'icad' => '250 269 591 980 918',
            'loof' => 'LOOF 2025.22677',
            'coat' => 'Brown tabby rosetted/spotted',
            'eyes' => 'Vert',
            'availability' => 'to_define',
            'availability_label' => 'À définir',
            'visibility' => 'visible',
            'price_mode' => 'hidden',
            'price' => null,
            'highlight' => 'Femelle brown tabby issue de lignées testées.',
            'description' => 'A Queen Wild du Diamant Sauvage est une femelle Bengal brown tabby rosetted/spotted, avec tests HCM, PKD et génétiques en cours par filiation.',
            'parents' => [
                'father' => 'Pardus-dei Tempête du Désert',
                'mother' => 'Ultimatum du Diamant Sauvage',
            ],
            'health' => [
                'hcm' => 'En cours (juin)',
                'pkd' => 'En cours (juin)',
                'fiv_felv' => 'Négatif',
                'pra_b' => 'En cours (négatif par filiation)',
                'pkdef' => 'En cours (négatif par filiation)',
                'parents_tests' => 'PRA-b & PKDef N/N',
            ],
            'gallery' => [],
            'featured' => false,
        ],

        [
            'slug' => 'amor-of-darkness-du-diamant-sauvage',
            'name' => 'Amor of Darkness du Diamant Sauvage',
            'short_name' => 'Amor of Darkness',
            'category' => 'female',
            'sex' => 'Femelle',
            'birth_date' => '2024-03-01',
            'birth_label' => '01 mars 2024',
            'icad' => '250 269 611 367 203',
            'loof' => 'LOOF 2025.14556',
            'coat' => 'Brown tabby rosetted/spotted',
            'eyes' => 'Or',
            'availability' => 'not_available',
            'availability_label' => 'Femelle',
            'visibility' => 'visible',
            'price_mode' => 'hidden',
            'price' => null,
            'highlight' => 'Femelle brown tabby au regard doré.',
            'description' => 'Amor of Darkness du Diamant Sauvage est une femelle Bengal brown tabby rosetted/spotted, avec tests santé et génétiques OK.',
            'parents' => [
                'father' => 'Pardus-dei Tempête du Désert',
                'mother' => 'Stars du Diamant Sauvage',
            ],
            'health' => [
                'hcm' => 'OK',
                'pkd' => 'OK',
                'fiv_felv' => 'Négatif',
                'pra_b' => 'N/N',
                'pkdef' => 'N/N',
                'parents_tests' => 'PRA-b & PKDef N/N',
            ],
            'gallery' => [],
            'featured' => false,
        ],

        [
            'slug' => 'pardusdei-xenallulah',
            'name' => 'Pardusdei Xenallulah',
            'short_name' => 'Xenallulah',
            'category' => 'female',
            'sex' => 'Femelle',
            'birth_date' => '2024-11-08',
            'birth_label' => '08 novembre 2024',
            'icad' => '250 269 591 767 404',
            'loof' => 'LOOF 2025.1781',
            'coat' => 'Seal silver mink tabby rosetted/spotted',
            'eyes' => 'Aigue-marine',
            'availability' => 'not_available',
            'availability_label' => 'Femelle',
            'visibility' => 'visible',
            'price_mode' => 'hidden',
            'price' => null,
            'highlight' => 'Femelle seal silver mink au regard aigue-marine.',
            'description' => 'Pardusdei Xenallulah est une femelle Bengal seal silver mink tabby rosetted/spotted, avec tests HCM, PKD et PRA-b OK.',
            'parents' => [
                'father' => 'Pardus-dei Uroboros',
                'mother' => 'Pardus-dei Tallulah',
            ],
            'health' => [
                'hcm' => 'OK',
                'pkd' => 'OK',
                'fiv_felv' => 'Négatif',
                'pra_b' => 'N/N',
                'pkdef' => 'N/K',
                'parents_tests' => null,
            ],
            'gallery' => [],
            'featured' => false,
        ],

        [
            'slug' => 'amara-du-diamant-sauvage',
            'name' => 'Amara du Diamant Sauvage',
            'short_name' => 'Amara',
            'category' => 'female',
            'sex' => 'Femelle',
            'birth_date' => '2025-08-23',
            'birth_label' => '23 août 2025',
            'icad' => '250 269 611 646 112',
            'loof' => 'LOOF 2025.46900',
            'coat' => 'Blue mink tabby rosetted/spotted',
            'eyes' => 'Bleus',
            'availability' => 'to_define',
            'availability_label' => 'À définir',
            'visibility' => 'visible',
            'price_mode' => 'hidden',
            'price' => null,
            'highlight' => 'Jeune femelle blue mink issue de lignées testées.',
            'description' => 'Amara du Diamant Sauvage est une femelle Bengal blue mink tabby rosetted/spotted, avec tests HCM, PKD et génétiques en cours par filiation.',
            'parents' => [
                'father' => 'DottyCat Gambling Man',
                'mother' => 'Thetrys de Laf',
            ],
            'health' => [
                'hcm' => 'En cours',
                'pkd' => 'En cours',
                'fiv_felv' => 'Négatif',
                'pra_b' => 'En cours (négatif par filiation)',
                'pkdef' => 'En cours (négatif par filiation)',
                'parents_tests' => 'PRA-b & PKDef N/N',
            ],
            'gallery' => [],
            'featured' => true,
        ],

    ],

];
